config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :time, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    set_date
    @events = Event.all.sort_by(&:time)
    @event = Event.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save 
      redirect_to '/events', notice: "Your event was succesfully created"
    else 
      render :new, notice: "Events cannot be made for the same time"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      (redirect_to '/events')
    else 
      render :edit, notice: "Events cannot be made for the same time"
    end
  end

  def destroy
    @event.destroy
    redirect_to '/events'
  end

  private
    def set_event
      @event = Event.find_by(id: params[:id])
    end

    def set_date
      @date = params.fetch(:start_date, Date.today).to_date
    end

    def event_params
      params.require(:event).permit(:name, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
  def weekday(date)
    date.strftime("%A")
  end

  def month_name(date)
    date.strftime("%B %Y")
  end

  def date_range(start_date)
    (start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week).to_a
  end

  def first_week_of_month(start_date)
    date_range(start_date).slice(0,7)
  end

  def display_time(event)
    event.time.strftime("%b %d, %Y %I:%M %p")
  end

end

app/views/events/_calendar.html.slim
.container
  = link_to "Previous", start_date: date_range(start_date).first - 1.day
  '
   
  = link_to "Next", start_date: date_range(start_date).last + 1.day
  h1.text-center
    = month_name(start_date)
  table.table.table-striped.table-bordered
    thead
      tr
        - first_week_of_month(start_date).each do | day | 
          th
            = weekday(day)

    tbody
      - date_range(start_date).each_slice(7) do |week|
        tr
          - week.each do |day| 
            td.text-center
              = day.day
              - @events.select{|e| e.time.to_date == day }.each do |event|
                .small
                  = event.name

app/views/events/_form.html.slim
= form_for @event do |f| 
 = f.label :event_name
 = f.text_field :name
 br

 = f.datetime_select :time 
 br

 = f.submit 

app/views/events/edit.html.slim
h1 Edit Event

= render "form"

app/views/events/index.html.slim
.container
  = render 'calendar', start_date: @date
  br
  br
  h3.text-center Upcoming Events
  - if !@events.empty?
    ul.list-group
    - @events.each do |event| 
      li.list-group-item
        h4 
          = event.name
        p
          = display_time(event)
        .btn-group
          button.btn.btn-light.btn-sm.btn-secondary
            = link_to "edit", edit_event_path(event)
          button.btn.btn-warning.btn-sm.btn-secondary
            = link_to "delete", event_path(event), method: :delete, data: {confirm: 'delete this event?' }
      br  
  - else
    p You have no scheduled events at this time.

  .container.new-event-form
    h1 New Event
    = render 'form', event: @event

app/views/events/new.html.slim
h4 Create a New Event

= render "form"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sawyer Calendar Code Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css", media: "all" %> 
  </head>

  <body>
    <div class='container'>

        <% unless flash.empty? %>
          <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-info" %>
          <% end %>
        <% end %>

      <h1 class="font-weight-light text-center">Sawyer Calendar Challenge </h1><br>
      <%= yield %>
    </div>
  </body>
</html>